### ISSUE TITLE
图片上传方法

### ISSUE THREAD

**Issue by dmnqmn** [dmnqmn/ExMum#12]
POST /photos/upload

|参数|类型|含义|
|---|---|---|
|photo|File|要上传的图片|

返回值 { "id": "图片上传后在数据库中的 id", "url": "生成的 url" }

POST /photos/new

|参数|类型|含义|
|---|---|---|
|photo|Number|刚刚上传的photo的id|
|tags|Array<String>|图片相关标签名|
|name|String|图片名|
|description|String>|图片描述|

**Comment by Foolyou** [comment]
已完成
