### ISSUE TITLE
展示用户个人信息接口

### ISSUE THREAD

**Issue by dmnqmn** [dmnqmn/ExMum#13]
rt

**Comment by woctober** [comment]
@Foolyou 个人主页 前端需要哪些数据？后端好传给你。参考链接：https://www.pinterest.com/settings

**Comment by Foolyou** [comment]
直接把 user 的 table 里的相关数据都传了就好了。

其实只需要写相关的取数据的函数，模板我自己填就行。

**Comment by Foolyou** [comment]
比如叫 User::getPersonalInfo()，然后返回一个 Object 就可以。模板的话回头我再看吧。

**Comment by dmnqmn** [comment]
#20
