### ISSUE TITLE
用户注册与登录

### ISSUE THREAD

**Issue by Foolyou** [dmnqmn/ExMum#2]
所有接口的返回都是 JSON 格式，使用 HTTP STATUS CODE 表示状态。

接口
1. POST /register 注册

|参数|类型|含义|
|---|---|---|
|email|String|邮箱，唯一|
|password|String|密码，加密|

返回值：
成功: 200，注册成功，响应中应设置用户 Cookie `EXMUM_U` 为对应的加密后的 AccessToken 值

失败：400，参数缺失(REGISTER_EMAIL_NEEDED, REGISTER_PASSWORD_NEEDED)或格式错误(REGISTER_EMAIL_ILLEGAL)
失败：403，邮箱已存在(REGISTER_EMAIL_EXISTED)

具体错误信息应在错误返回的 JSON 中的 error 字段，如 `{ "error": "LOGIN_EMAIL_EXISTED" }`。
错误名称应当全局唯一，格式为 `接口名_错误简述`。

2. 登录
POST /login 登录

|参数|类型|含义|
|---|---|---|
|email|String|邮箱|
|password|String|密码，加密|

返回值：
成功：200，验证通过，后端应在响应中设置用户 Cookie `EXMUM_U` 为对应加密后的 AccessToken 值

失败：403，用户密码验证未通过(LOGIN_WRONG_PASSWORD)
失败：404，用户账号不存在(LOGIN_USER_NOT_FOUND)

3. 登出
POST /logout 登出

返回值：
成功: 200，用户 Cookie 中携带的 token 存在，并且成功删除。后端应在响应中将 Cookie 中的 `u` 字段清空。

失败：403，token 验证未通过(LOGOUT_UNAUTHORIZED)

4. 修改密码
POST /password 修改密码

|参数|类型|含义|
|---|---|---|
|password|String|旧密码，加密|
|newPassword|String|新密码，加密|

返回值：
成功：200，密码成功修改。

失败：400，没有密码或新密码字段(PASSWORD_PASSWORD_NEEDED, PASSWORD_NEW_PASSWORD_NEEDED)
失败：403，用户 AccessToken 验证未通过，旧密码错误(PASSWORD_UNAUTHORIZED)

**Comment by woctober** [comment]
nice

**Comment by Foolyou** [comment]
直接使用 Cookie，不另带 token 了。

**Comment by Foolyou** [comment]
@dmnqmn @woctober 注意一下本页进行了修改，后续开发按新的接口来。

关于接口细节以及参数、返回值的格式有什么需要修正的吗？

**Comment by Foolyou** [comment]
@dmnqmn @woctober  在后面的接口定义中也请定义好每一个错误对应的 error，通过 JSON 格式传递到前端。这样我们可以统一错误处理。

**Comment by Foolyou** [comment]
已经写了一个 /register 接口，同时完成了 AccessToken 和密码生成方案的改造。

剩余的几个接口可以参考 /register 接口实现，cookie 生成可以直接使用 `makeCookie(name, value, maxAge)` 这个函数。主要是验证密码以及操作 token。

请注意请求及相应的数据格式均为 JSON 格式，后端向前端报错时利用 HTTP 状态码以及响应中的 error 字段。

**Comment by Foolyou** [comment]
Cookie 加入了域名限制，请在本地测试环境中添加 hosts:
```
192.168.33.20 exmumdev.com www.exmumdev.com
```

**Comment by Foolyou** [comment]
已完成
