### ISSUE TITLE
新增相册表--gallery 

### ISSUE THREAD

**Issue by woctober** [dmnqmn/ExMum#31]

**Comment by woctober** [comment]
1. gallery 表

| 字段 | 类型&长度 |  是否为空 | 意义 | 
| --------   | -----:  | :----:   |     -----:  | 
| id | int | not null |  |
| uid | int | not null | 上传用户 id |
| name | int | not null | 上传用户 name |
| tag_id | 1{默认值} | not null | 相册的tag |
| description | varchar(255) | | 相册描述 |
| secret | 0{不隐私，默认值}, 1{隐私} | not null | 相册是否隐私 |
| created_at | int | not null | 相册创建时间 |
| updated_at | int | not null | 相册更新时间 |

2. photo 表中增加两个字段：

| 字段 | 类型&长度 |  是否为空 | 意义 | 
| --------   | -----:  | :----:   |     -----:  | 
| gallery_id | int | not null | 相册 id |
| original_id | int | | 原始上传的 id |

**Comment by Foolyou** [comment]
👍
