### ISSUE TITLE
User 相关改进

### ISSUE THREAD

**Issue by Foolyou** [dmnqmn/ExMum#35]
1. 已经添加了 User <-> User 的 follow 关系，User::isFollowing 函数应当改为 User::isFollowingTags 以区别对 tag 和 user 的 follow

2. GET /user/follow 应当改为 GET /user/following，并添加 GET /user/followedBy，用于获取用户关注的人列表及其关注者列表。

3. GET /user/following, GET /user/followedBy 不存在特殊的需求，分页建议改为 Laravel 自带的分页。或是将现有数据格式修改为如下格式，以支持显示用户关注者数量：
```
{
    total: 数据总量,
    page: 当前页数,
    total_page: 总页数,
    data: [实际数据列表]
}
```
分页应当支持 page 和 results_per_page 两个参数，分别表示请求的页数，以及每页数据量。

**Comment by dmnqmn** [comment]
done
