### ISSUE TITLE
table

### ISSUE THREAD

**Issue by woctober** [dmnqmn/ExMum#6]
user 表

| 字段 | 类型&长度 |  是否为空 | 意义 | 
| --------   | -----:  | :----:   |     -----:  | 
| id | int | not null | 用户 id |
| first_name | varchar(10) |  | 用户的姓 |
| last_name | varchar(10) |  | 用户的名
| user_name | varchar(50) |  | 用户个人主页的用户名（默认为邮箱前缀） |
| gender | 0{未知，默认值},1{女性},2{男性} | not null | 性别 |
| password | varchar(50) | not null | 用户密码|
| phone | int |  | 注册电话 |
| email | varchar(50) |  | 用户注册邮箱|
| status | tinyint | not null | 用户激活状态 |
| avatar | varchar(50)  |  | 用户头像|
| description | varchar(255) |  | 用户个性签名 |
| tags | varchar(50) |  | 用户喜欢的标签 |

user_follow 表

| 字段 | 类型&长度 |  是否为空 | 意义 | 
| --------   | -----:  | :----:   |     -----:  | 
| id | int | not null |  |
| uid | int | not null | 用户 id |
| follow_uid | int | not null | 关注用户 id |

photo 表

| 字段 | 类型&长度 |  是否为空 | 意义 | 
| --------   | -----:  | :----:   |     -----:  | 
| id | int | not null | 图片 id |
| url |  varchar(50) | not null | 图片上传地址 |
| uid | int | not null | 上传图片用户 id |
| tag1 | tinyint|  | 美女(图片分类名称) |
| tag2 | tinyint |  | 汽车 |
 ...
| tag22 | tinyint | | 游戏 |

copy_photo 表

| 字段 | 类型&长度 |  是否为空 | 意义 | 
| --------   | -----:  | :----:   |     -----:  | 
| id | int | not null |  |
| uid | int | not null | 用户 id |
| photo_id | int | not null | 图片 id |
| photo_book_id | int | not null | 相册 id |

photo_book 表

| 字段 | 类型&长度 |  是否为空 | 意义 | 
| --------   | -----:  | :----:   |     -----:  | 
| id | int | not null | 用户相册 id | 
| uid | int | not null | 创建相册用户 id |
| name | varchar(20) | not null | 相册名称 |

**Comment by dmnqmn** [comment]
@Foolyou 帮 check 一下吧

**Comment by Foolyou** [comment]
LGTM，另外应该还需要一个 user_token 来记录用户的 AccessToken。

**Comment by Foolyou** [comment]
是否需要一个 gallery 表，用于用户创建不同的相册。

@dmnqmn
