### ISSUE TITLE
一期主要页面

### ISSUE THREAD

**Issue by Foolyou** [dmnqmn/ExMum#8]
exmum 设计上是一个偏展示型的网站，考虑的 SEO 的因素，以及开发上的方便，决定直接使用 Laravel 的 View 层作为前端的基础，只在少数功能型页面使用 Vue。

页面基本定义如下：

```
/ => 首页；未登录状态下弹出登录/注册 Modal，默认显示热门；登录状态下默认显示用户关注的动态
/user/:userName => 用户的个人主页
/gallery/:gallerySlug => 相册的展示页面
/topic/topicName => 话题对应的主页
/photo/photoId => 照片
```

@dmnqmn 
@woctober 

请看一下是否合理。

**Comment by Foolyou** [comment]
前端页面将使用 blade 模板。

前端入口文件将会放置到 resources/assets/js/entry/ 目录下。

**Comment by dmnqmn** [comment]
可以的

**Comment by Foolyou** [comment]
上传、单图、首页、用户设置已完成。
